### ISSUE TITLE
Merge into idris-hackers/idris-lens

### ISSUE THREAD

**Issue by langston-barrett** [HuwCampbell/idris-lens#6]
Any reason to have two separate repos? https://github.com/idris-hackers/idris-lens

**Comment by HuwCampbell** [comment]
That one doesn't use van Laarhoven lenses, but rather the Store comonad, so it's more like Data.Lens instead of Control.Lens.

**Comment by langston-barrett** [comment]
Ah, I betray my lack of understanding :smile: Thanks for the quick response!
